services:
  n8n:
    image: n8nio/n8n:latest
    user: "node"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - NODE_ENV=production
      - N8N_PATH_DATA=/home/node/.n8n
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_SECURE_COOKIE=false
    ports:
      - "5678:5678"
    volumes:
      - /opt/statement-analytics/data/.n8n:/home/node/.n8n
    restart: unless-stopped
    networks:
      - statement-network
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3001:3000"
    volumes:
      - /opt/statement-analytics/data/db:/data:ro
      - /opt/statement-analytics/data/metabase:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_DB_TYPE=h2
      - JAVA_TIMEZONE=UTC
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxRAMPercentage=75 -Xmx512m
      - MB_EMOJI_IN_LOGS=false
      - MB_APPLICATION_NAME=StatementAnalytics
      - MB_ADMIN_EMAIL=${METABASE_ADMIN_EMAIL}
      - MB_ADMIN_PASSWORD=${METABASE_ADMIN_PASSWORD}
    restart: unless-stopped
    networks:
      - statement-network
    mem_limit: 768m
    mem_reservation: 512m

networks:
  statement-network:
    driver: bridge

volumes:
  metabase-data:
    driver: local